title: Ohjelmistoprojekti 2
email: kalle.ilves@haaga-helia.fi
description: >-
  Ohjelmistoprojekti 2 -kurssimateriaali
baseurl: ""
url: ""
theme: just-the-docs
plugins:
  - jekyll-feed
mermaid:
  version: "11.4.1"
teacher_text: "Kalle Ilves (kalle.ilves@haaga-helia.fi) ja Jukka Juslin (jukka.juslin@haaga-helia.fi)"
teaching_sessions_text: "torstaisin klo 11:00 - 13:45 luokassa 5006 (sis. 40min lounastauon)"
final_deadline: "17.5. klo 23:59"
callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Tärkeää!
    color: red
  highlight:
    title: Huomio!
    color: yellow
  note:
    title: Vinkki
    color: purple

